swagger: "2.0"
info:
  description: "Objection API documentation"
  version: "1.0.0"
  title: "Objection"
  contact: 
    email: "clad.up@clad-up.com"
host: "localhost:5000"
basePath: "/api/v1"
tags:
- name: "objects"
  description: "Managing objects"
schemes:
- "http"
- "https"
paths:
  /objects/{component}/{type}/{key}:
    get:
      tags:
      - "objects"
      summary: "Get object by alias"
      description: "Returns the object of component, type, key"
      produces:
      - "application/json"
      parameters:
      - name: "component"
        in: "path"
        description: "Component of object: background, product, etc."
        required: true
        type: "string"
      - name: "type"
        in: "path"
        description: "Type of object: graphic, image"
        required: true
        type: "string"
        format: "int64"
      - name: "key"
        in: "path"
        description: "Primary key of product or campaign"
        required: true
        type: "integer"
        format: "int64"
      responses:
        404:
          description: "Object not found"
  /objects:
    post:
      tags:
      - "objects"
      summary: "Upload a graphic model or image"
      description: "Uploads to staging area and gives object name for aliasing"
      consumes:
      - "multipart/form-data"
      produces:
      - "application/json"
      parameters:
      - name: "object_file"
        in: "formData"
        description: "The graphic or image file"
        required: true
        type: "file"
      responses:
        400:
          description: "object_file empty, no file, not allowed file extension"
  /objects/{name}:
    patch:
      tags:
      - "objects"
      summary: "Alias object with name in path"
      description: "The alias will be used for getting the object. Alias format: {background_sphere|background_curve|background_skybox|background_floor|product}/{graphic|image}/{PK}"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "name"
        in: "path"
        description: "Name of object in Google Cloud Storage"
        required: true
        type: "string"
      - name: "alias"
        in: "body"
        description: "The alias for calling the object which has path's name"
        required: true
      responses:
        400:
          description: "Alias is missing"
        404:
          description: "Object with name not found"
    delete:
      tags:
      - "objects"
      summary: "Unalias object with name in path"
      description: "When unaliased, the object will not be callable with that object anymore."
      produces:
      - "application/json"
      parameters:
      - name: "name"
        in: "path"
        description: "Name of object in Google Cloud Storage"
        required: true
        type: "string"
      responses:
        404:
          description: "Object with name not found"

